# Site settings
title: "Burhanettin Nacar"
description: "Burhanettin Nacar's personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Settings
avatar:                  "true"
name:                    "Burhanettin Nacar"
job_title:               "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
contact_email:           "mtbnacar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
contact_telephone:       ""
contact_address:         ""

header_contact_info:     ""
display_header_contact_info:    "false"

header_intro: "<p>10 years of experience building reliable backend systemsâ€”now focused on applied AI. Designing and
implementing solutions that blend microservices with LLMs to automate workflows, developing
custom MCP servers to extend AI capabilities, creating custom GitHub Copilot agents, and shipping
smarter, scalable features end to end. Combining strong fundamentals in distributed systems with
hands-on AI implementation to solve real business problems.</p>"

looking_for_work:        "yes"

section_experience:      true
section_education:       true
# section_projects:        true
# section_skills:          true
# section_recognition:     true
# section_links:           true
# section_associations:    true
section_interests:       true

# Social links
social_links:
  github_url:            "https://github.com/uppnrise"
  twitter_url:           "https://x.com/uppnrise"
  # dribbble_url:          "https://dribbble.com/"
  # facebook_url:          "insert Facebook URL here"
  linkedin_url:          "https://www.linkedin.com/in/burhanettin-nacar"
  instagram_url:         "https://www.instagram.com/brhnt.nacar"
  website_url:           "https://bnacar.dev"
  medium_url:            "https://medium.com/@bnacar"
print_social_links:      true

# Design settings
resume_theme:                   default
